name: nibbles_ecommerce
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  buttons_tabbar: null
  carousel_slider: null
  cloud_firestore: null
  connectivity_plus: null

  cupertino_icons: ^1.0.2
  equatable: null
  firebase_auth: null
  firebase_core: null
  firebase_messaging: null
  flutter:
    sdk: flutter
  flutter_barcode_scanner: null
  flutter_bloc: null
  flutter_local_notifications: null
  flutter_svg: null
  smooth_page_indicator: null
  table_calendar: null
  url_launcher: null
  stylish_bottom_bar: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
 

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
    - assets/png/categories/
    - assets/png/meals/
    - assets/png/offers/
    - assets/png/social/
    - assets/png/steps/
    - assets/png/products/
    - assets/png/payment/

  fonts:
    - family: Form
      fonts:
        - asset: assets/fonts/Form-Medium.ttf
          weight: 600
        - asset: assets/fonts/Form-Light.ttf
          weight: 200
        - asset: assets/fonts/Form-Bold.ttf
          weight: 900
